---
title: "data wragling"
format: html
editor: visual
---

# Load Library

```{r}
library(tidyverse)
library(lubridate)
```

# Import Data

```{r}
# Membaca data mentah dari folder data/raw
aktor <- read_csv('../data/raw/aktor.csv')
film <- read_csv('../data/raw/filmm.csv')
reviews <- read_csv('../data/raw/reviews.csv')
sutradara <- read_csv('../data/raw/sutradara.csv')
```

```{r}
# Melihat struktur awal data untuk memahami kolom dan tipe datanya
glimpse(film)
glimpse(sutradara)
glimpse(aktor)
glimpse(reviews)
```

```{r}
# Cek nama kolom untuk memastikan keselarasan sebelum proses penggabungan
colnames(film)
colnames(sutradara)
colnames(aktor)
colnames(reviews)
```

# Menggabungkan Semua Data

```{r}
merged_df <- film %>%
  left_join(aktor, by = 'id_film') %>%
  left_join(reviews, by = 'id_film') %>%
  left_join(sutradara, by = c('id_film'))

glimpse(merged_df)
```

# Menghapus Kolom Yang Sama

```{r}
merged_df <- merged_df %>%
  select(-id_sutradara.x, -id_aktor.x, -id_aktor.y, -tahun_rilis.y, -id_user, -id_sutradara.y)

colnames(merged_df)
```

# Mengganti Nama Kolom

```{r}
merged_df <- merged_df %>%
  rename(
    film_id = id_film,
    title = judul_film,
    release_year = tahun_rilis.x,
    duration = durasi_film,
    genre = genre_film,
    vote_count = votes,
    film_rating = rating,
    actors = nama_aktor,
    reviewer_name = nama_user,
    review_date = tanggal_user,
    review_content = isi_user,
    review_rating = rating_user,
    director = nama_sutradara
  )%>%
  mutate(review_date = dmy(review_date))

colnames(merged_df)
```

# Membuat Tabel-tabel Baru

```{r}
# 1. Tabel Directors
directors <- merged_df %>%
  select(director) %>%
  distinct() %>%
  arrange(director) %>%
  mutate(director_id = sprintf("D%04d", row_number())) %>%
  relocate(director_id)

# 2. Tabel Films
films <- merged_df %>%
  select(title, release_year, duration, genre, vote_count, film_rating, director) %>%
  distinct() %>%
  left_join(directors, by = "director") %>%
  select(title, release_year, duration, genre, vote_count, film_rating, director_id) %>%
  arrange(title) %>%
  mutate(film_id = sprintf("F%04d", row_number())) %>%
  mutate(duration = as.integer(gsub(" min", "", duration))) %>% 
  relocate(film_id)

# 3. Tabel Actors
actors <- merged_df %>%
  select(actors) %>%
  separate_rows(actors, sep = "; ") %>%
  distinct() %>%
  arrange(actors) %>%
  filter(actors != "nan") %>% 
  mutate(actor_id = sprintf("A%04d", row_number())) %>%
  rename(actor_name = actors) %>%
  relocate(actor_id)

# 4. Tabel Casting
casting <- merged_df %>%
  select(title, actors) %>%
  separate_rows(actors, sep = "; ") %>%
  distinct() %>%
  filter(actors != "nan") %>%
  left_join(actors, by = c("actors" = "actor_name")) %>%
  left_join(films %>% select(film_id, title), by = "title") %>%
  select(film_id, actor_id) %>% 
  filter(!is.na(actor_id))

# 5. Tabel Reviewers
reviewers <- merged_df %>%
  select(reviewer_name) %>%
  distinct() %>%
  arrange(reviewer_name) %>%
  mutate(reviewer_id = sprintf("R%04d", row_number())) %>%
  relocate(reviewer_id)

# 6. Tabel Reviews
film_lookup <- films %>%
  select(film_id, title)

reviews <- merged_df %>%
  left_join(film_lookup, by = "title") %>%
  left_join(reviewers, by = "reviewer_name") %>%
  mutate(
    film_id = film_id.y,
    review_id = sprintf("RV%04d", row_number())
  ) %>%
  select(review_id, film_id, reviewer_id, review_date, review_content, review_rating)
```

# Menyimpan Tabel-tabel tersebut

```{r}
# Simpan tabel Directors
write_csv(directors, '../data/clean/directors.csv')

# Simpan tabel Films
write_csv(films, '../data/clean/films.csv')

# Simpan tabel Actors
write_csv(actors, '../data/clean/actors.csv')

# Simpan tabel Casting
write_csv(casting, '../data/clean/casting.csv')

# Simpan tabel Reviewers
write_csv(reviewers, '../data/clean/reviewers.csv')

# Simpan tabel Reviews
write_csv(reviews, '../data/clean/reviews.csv')
```
